<?php

return [
    'groups' => [
        'general' => [
            'label' => 'General',
            'fields' => [
                'site_name' => ['label' => 'Site Name', 'type' => 'text'],
                'site_tagline' => ['label' => 'Site Tagline', 'type' => 'text'],
                'site_logo_letter' => ['label' => 'Logo Letter', 'type' => 'text'],
                'footer_description' => ['label' => 'Footer Description', 'type' => 'textarea'],
            ],
        ],
        'contact' => [
            'label' => 'Contact Info',
            'fields' => [
                'contact_address' => ['label' => 'Address', 'type' => 'textarea'],
                'contact_email' => ['label' => 'Email', 'type' => 'email'],
                'contact_support_email' => ['label' => 'Support Email', 'type' => 'email'],
                'contact_phone' => ['label' => 'Phone', 'type' => 'text'],
                'contact_hours' => ['label' => 'Working Hours', 'type' => 'text'],
            ],
        ],
        'home' => [
            'label' => 'Home Page',
            'fields' => [
                'home_hero_badge' => ['label' => 'Hero Badge', 'type' => 'text'],
                'home_hero_title' => ['label' => 'Hero Title Line 1', 'type' => 'text'],
                'home_hero_title_highlight' => ['label' => 'Hero Title Line 2', 'type' => 'text'],
                'home_hero_description' => ['label' => 'Hero Description', 'type' => 'textarea'],
                'home_stat_students' => ['label' => 'Students Count', 'type' => 'text'],
                'home_stat_teachers' => ['label' => 'Teachers Count', 'type' => 'text'],
                'home_stat_assignments' => ['label' => 'Assignments Count', 'type' => 'text'],
                'home_stat_satisfaction' => ['label' => 'Satisfaction Rate', 'type' => 'text'],
                'home_cta_title' => ['label' => 'CTA Title', 'type' => 'text'],
                'home_cta_description' => ['label' => 'CTA Description', 'type' => 'textarea'],
            ],
        ],
        'about' => [
            'label' => 'About Page',
            'fields' => [
                'about_hero_title' => ['label' => 'Hero Title', 'type' => 'text'],
                'about_hero_subtitle' => ['label' => 'Hero Subtitle', 'type' => 'textarea'],
                'about_story_title' => ['label' => 'Story Title', 'type' => 'text'],
                'about_story_text_1' => ['label' => 'Story Paragraph 1', 'type' => 'textarea'],
                'about_story_text_2' => ['label' => 'Story Paragraph 2', 'type' => 'textarea'],
                'about_years' => ['label' => 'Years Experience', 'type' => 'text'],
                'about_happy_students' => ['label' => 'Happy Students', 'type' => 'text'],
                'about_expert_teachers' => ['label' => 'Expert Teachers', 'type' => 'text'],
                'about_mission' => ['label' => 'Mission', 'type' => 'textarea'],
                'about_vision' => ['label' => 'Vision', 'type' => 'textarea'],
            ],
        ],
        'student' => [
            'label' => 'Student Page',
            'fields' => [
                'student_hero_title' => ['label' => 'Hero Title', 'type' => 'text'],
                'student_hero_subtitle' => ['label' => 'Hero Subtitle', 'type' => 'textarea'],
                'student_section_title' => ['label' => 'Section Title', 'type' => 'text'],
                'student_section_description' => ['label' => 'Section Description', 'type' => 'textarea'],
            ],
        ],
        'teacher' => [
            'label' => 'Teacher Page',
            'fields' => [
                'teacher_hero_title' => ['label' => 'Hero Title', 'type' => 'text'],
                'teacher_hero_subtitle' => ['label' => 'Hero Subtitle', 'type' => 'textarea'],
                'teacher_section_title' => ['label' => 'Section Title', 'type' => 'text'],
                'teacher_section_description' => ['label' => 'Section Description', 'type' => 'textarea'],
            ],
        ],
        'mail' => [
            'label' => 'Mail Setup',
            'fields' => [
                'mail_mailer' => [
                    'label' => 'Mailer',
                    'type' => 'select',
                    'options' => [
                        'smtp' => 'SMTP',
                        'log' => 'Log file (testing)',
                        'sendmail' => 'Sendmail',
                    ],
                    'hint' => 'Use SMTP for live ticket emails. Log writes to storage/logs instead of sending.',
                ],
                'mail_host' => ['label' => 'SMTP Host', 'type' => 'text', 'hint' => 'Example: smtp.gmail.com'],
                'mail_port' => ['label' => 'SMTP Port', 'type' => 'text', 'hint' => '587 for TLS, 465 for SSL'],
                'mail_encryption' => [
                    'label' => 'Encryption',
                    'type' => 'select',
                    'options' => [
                        'tls' => 'TLS',
                        'ssl' => 'SSL',
                        '' => 'None',
                    ],
                ],
                'mail_username' => ['label' => 'SMTP Username', 'type' => 'text'],
                'mail_password' => ['label' => 'SMTP Password', 'type' => 'password', 'hint' => 'Leave blank to keep the saved password.'],
                'mail_from_address' => ['label' => 'From Email', 'type' => 'email'],
                'mail_from_name' => ['label' => 'From Name', 'type' => 'text'],
                'mail_admin_email' => [
                    'label' => 'Admin Ticket Email',
                    'type' => 'email',
                    'hint' => 'New tickets and user replies are sent here.',
                ],
            ],
        ],
        'contact_page' => [
            'label' => 'Contact Page',
            'fields' => [
                'contact_hero_title' => ['label' => 'Hero Title', 'type' => 'text'],
                'contact_hero_subtitle' => ['label' => 'Hero Subtitle', 'type' => 'textarea'],
            ],
        ],
        'exam' => [
            'label' => 'Exam Paper',
            'fields' => [
                'exam_default_instructions' => [
                    'label' => 'Default Exam Instructions',
                    'type' => 'textarea',
                    'rows' => 8,
                    'hint' => 'Write one instruction per line. Each line appears as a numbered point on the exam paper.',
                ],
            ],
        ],
    ],

    'defaults' => [
        'site_name' => 'Gses Chaturji',
        'site_tagline' => 'Gujarat School of Excellence System',
        'site_logo_letter' => 'G',
        'footer_description' => 'Gses Chaturji — a modern learning platform connecting students, teachers, and administrators. विद्या ददाति विनयम्',
        'contact_address' => '123 Education Street, Learning City',
        'contact_email' => 'info@gseschaturji.com',
        'contact_support_email' => 'support@gseschaturji.com',
        'mail_mailer' => 'smtp',
        'mail_host' => 'smtp.gmail.com',
        'mail_port' => '587',
        'mail_encryption' => 'tls',
        'mail_username' => '',
        'mail_password' => '',
        'mail_from_address' => 'noreply@gseschaturji.xyz',
        'mail_from_name' => 'Gses Chaturji',
        'mail_admin_email' => 'support@gseschaturji.com',
        'contact_phone' => '+91 98765 43210',
        'contact_hours' => 'Mon - Sat, 9AM - 6PM',
        'home_hero_badge' => 'Gujarat School of Excellence System',
        'home_hero_title' => 'Learn with Excellence.',
        'home_hero_title_highlight' => 'Grow with Humility.',
        'home_hero_description' => 'Manage homework, connect students with teachers, and track progress — all from one beautiful, easy-to-use platform.',
        'home_stat_students' => '500+',
        'home_stat_teachers' => '50+',
        'home_stat_assignments' => '1000+',
        'home_stat_satisfaction' => '98%',
        'home_cta_title' => 'Ready to Get Started?',
        'home_cta_description' => 'Join our platform today and experience smarter homework management.',
        'about_hero_title' => 'Empowering Education Through Technology',
        'about_hero_subtitle' => 'We are dedicated to making homework management simple, effective, and accessible for everyone.',
        'about_story_title' => 'Our Story',
        'about_story_text_1' => 'Homework was built with a simple vision — to help students stay organized and help teachers manage assignments effortlessly. We believe technology should make learning easier, not harder.',
        'about_story_text_2' => 'From tracking daily homework to connecting students with their teachers, our platform brings everything together in one secure and user-friendly place.',
        'about_years' => '10+',
        'about_happy_students' => '500+',
        'about_expert_teachers' => '50+',
        'about_mission' => 'To simplify homework management and improve learning outcomes for every student.',
        'about_vision' => 'To become the most trusted homework platform for schools and educators worldwide.',
        'student_hero_title' => 'Your Learning Journey Starts Here',
        'student_hero_subtitle' => 'Track homework, submit assignments, and stay on top of your studies with ease.',
        'student_section_title' => 'Built for Students',
        'student_section_description' => 'Never miss a homework deadline again. Our student portal gives you a clear overview of all pending, submitted, and graded assignments. Stay organized, communicate with your teachers, and focus on what matters most — learning and growing.',
        'teacher_hero_title' => 'Teach Smarter, Manage Better',
        'teacher_hero_subtitle' => 'Create assignments, review submissions, and guide your students with powerful tools.',
        'teacher_section_title' => 'Empower Your Teaching',
        'teacher_section_description' => 'Save time on homework management and focus on what you do best — teaching. Assign work, review submissions, and provide feedback all from one dashboard. Our teacher portal is designed to streamline your workflow and help you stay connected with every student.',
        'contact_hero_title' => 'Get In Touch With Us',
        'contact_hero_subtitle' => 'Have a question or need help? We would love to hear from you.',
        'exam_default_instructions' => "Read all questions carefully before answering.\nWrite neat and legible answers.\nDo not copy from others.",
    ],
];
